#+BEGIN_HTML
---
layout: page
title: Madagascar Team 1 expedition 1997
---
#+END_HTML

* Madagascar Team 1 expedition 1997


** Introduction (Catherine, February 2, 1997)
In the Christmas term of 1996 the fifth and sixth form received a visit from Camilla Blood - a representative from World Challenge. She talked to us about taking part in an expedition, the opportunities to develop in maturity, leadship skills and responsibility. The challenge of surviving in a foreign country for a month with an alien culture. The amazing signs and, of course, leeches, insects, altitude sickness, fatigue and stomach upsets. Undeterred, over 36 people expressed an interest in taking part (encouraged by favourable reports from the Upper VI who had travelled to Equador). It was decideed that, to allow everybody who so wished to go, two teams would be formed. Team 1 was to be led by Mr George and Team 2 by Mr Gambles. We each nominated one other person whom we wanted to be in a team with and left the two teachers with the task of splitting the group. We had an initial team meeting later that term in which we started to talk about fitness, fund-raising and an itinerary but little definite was set out. In February, World Challenge organised an evening in which parents could come and hear about the company and about previous expeditions. We were also issued with a World Challenge prospectus and a parents' brief which outlined a proposed itinerary, booking, legal and insurance arrangements. We were recommended to find out as much as possible about Madagascar and to start fund-raising as soon as possible.

** Early days (Catherine, February 3, 1997)
After this we established a planning and a fund-raising committee for our team. Various fund-raising ideas were put forward but the only one whichcame to fruition was to gain sponsorship from Barclay's bank (who paid for team T-shirts to be printed). In this we were put to shame by group 2 who organised weekly cake sales and, in doing, raised substantial amounts. The planning committee felt limited by a lack of knowledge of what we could do and about Madagascar. After reading th World Challenge information and leaflets which Pip had sent for, taking into account limited finance, we proposed a rough plan - subject to change after the recce team from World Challenge returned from Madagascar with information on what we could feasibly achieve. The first team fund-raising event was a car wash at the Summer Fair and, for a donation from the parents association, to help set the air up (moving tables and chairs). Unfortunately few people from the group actually came although those who did were tireless. Hannah noticeable was excellent at getting money out of people (charging extra to dry the car!). Individual fund-raising was in various stges with some people having taken up weekend work and others depending on parental support (personally I was paying off a debt for the school skiing holiday I was going on). In the Autumn term both teams along with the boys hockey and rugby and cross-country teams had a bleep test on the tennis courts in full view of a large audience, most people proved to be relatively fit (but others, including myself, had cause to be embarrassed). About a week after this we were issued with a fitness program. For someone who cannot run upstairs, running three miles thrice weekly in a non street lit area was going to be a problem. This term also saw the introduction of weekly shoe cleaning sessions. They were discontinued after Christmas being deemed not worth the effort. A series of car boot sales occurred and the initial planning of a Boxercise and a wine tasting evening were set up. Early that term a magazine committee had been set up. We hoped to publish a magazine to inform the rest of the school of our magazine and maybe, attract sponsorship. To cover the cost of printing we contacted various companies about advertising. The response was very limited and ultimately the project was abandoned. A second venture, A Madagascan evening with Keith Floyd, was also abandoned due to the cost of setting it up. It was during this term that a member of the recce team from World Challenge came to talk to us and, later on in the evening, to our parents. She showed us where she had been and of three community projects with which we could probably help. She outlined feasible areas to cover and then the two teams planned their itineraries. After much discussion (admittedly between few people) we decided upon a firm itinerary. Later she showed us slides of her travels and told of her experiences. It sounded wonderful. The teams by now had lost/gained some members. Ours now consisted of 16 pupils and Martin George. One Sunday morning in January 1997 we had another team meeting. Here the planning of the Boxercise (which will consist of 24 hours of circuit training) and the wine tasting evening (to which hopefully Keith Floyd will be able to come) was continued. These will be run by the Lower VI so Helena and I though of further events we could run and are, at present, researching them (ie trying to get donations of raffle prizes, and looking into a coach trip). That week saw our first raffle. This was at the third year boys parents evening and raised .45. The prizes were items of pottery which had been donated to us. Hopefully this success will be repeated at future events. 

** Wine tasting (Dave, February 4, 1997)
The revelation that Mr Huntington leads a double life proved to be valuable asset to the group. Secretly, the innocent and naive one is in cahootswith a dark and mysterious figure and together they are engaged in an undercover operation to take control of the alcoholic world. Hunto's partner in crime, the excellent Jim, is an unlikely villain: plump, jovial, piggy eyes poking out from an extraordinary (possibly paranormal) pair of eyebrows and piggy mouth poking out from behind an implausible moustache. Jim, with his huge crop of wild, silver curls has none of the obvious markings of a fascist dictator. However, be not deceived. The vile pair proceeded to tantalise the assembled gatherers with a collection of universally hideous potions. Each so called wine was treated by us, the innocent victims of their power hungry mind experiment, with equal disdain and yet, the tests appeared to have proved successful as, at the end of the evening, the weak minded fools were queuing up to buy the concoctions by the crate-load. The malicious duo are now loose in society practising their evil ways and so all that remains is for me to reveal the antidote to the brain washing which they perform with nonchalant aplomb. The only method of resistance is the taking up of a brass-band instrument; I'd like to teach the world to swing and save us from the iron rule of a portly connoisseur. 

** Build up (Kay, July 10, 1997)
And finally, the day arrived. Well almost. Being waved off into the Sports Hall didn't quite justify the tearful farewells. I don't think it's quite sunk in yet - we're going to Madagascar tomorrow. The first event on the lists was putting up the tents. A seemingly simple task, except that we had never seen this type of tent before. However, after a few false starts, ripped fly sheets and bent tent pegs, the tents were finally up. And taken down again. The rest of the day passed fairly uneventfully - handing out kit, discussing expectations and handing out jobs. I was hoping for a fire at the barbecue just so I'd have something to write about, but apart from few cremated sausages, everything went smoothly. We all finally got to sleep, despite Graeme's snoring, at some time after 11pm.


** Leaving school (Kay, July 11, 1997)
After getting up at the ridiculous time of 5.30 am, re-packing rucksacks, strapping down everything that moved and plastering everything with silver tape, we were almost ready to set off. With much groaning and muttering, rucksacks were heaved onto backs for the short distance to the bus. Our driver was the infamous Fabio - which was slightly worrying as he was also our driver during the Biology field trip, where he bus broke down three times. But we managed to reach Heatehrow airport in plenty of time and without any mishaps. The rucksacks were manouvered into the airport and stacked in mountain-high piles with various people standing guard. Last minute shopping for me consisted of extra pairs of socks and some chocolate to take away the taste of aeroplane food (which was, of course, disgusting, but we haven't even got on the plane yet). Nat and Suzanne bid farewell to their blokies (very sweet, aahh). Next was passport control and customs. Everything was fine untile Charley went through with the pade. She was releived not to have to explain why she was carrying a spade - she might have received a few strange looks. We proceeded to look at the departures board, which calmly told us that the last call for our light was 8 minutes ago. We of course, being the organised and structured team that we are, did not panic, but made our way to the departure lounge in a quick-march. No-one got on the plane for another hour, but never mind. Eventually we got on Flight BD0177 and took off. Pokey coped admirably well with his first flight ever, which was quite disappointing. I could have done with something exciting to write. Never mind. Food on the plan was, as predicted, only barely edible. The airlne conveniently forgot about there being any vegetarians on board, so Suzanne and Catherine probably had to fight for their meals. At lease the chocolate was OK though. We reached CDG more or less on time, and as we were getting off, the crew gave us a good luck message over the tanoy system which was very nice, even if repeating it in French was a bit pointless. Next shock of the day was being spoken to in French. OK, so we were in France, but it was still a shock. We took over a little shuttely-bus-thing to get to the next terminal, then had a look round the French duty free shops. We eventually boarded - except they'd forgotten to attach a plane to the end of the shuttely-connecty thing. Anyway, this is getting amazingly boring, so I'll just do a few more points:The stewardess didn't speak English (well didn't to me anyway) I was surrounded by French scouts and other frogs who kept trying to talk to me. I have forgotten every word of French I know (which wasn't much to start with) We had an hours wait to refuel at Munich - this really reflects the attitude in Madagascar - laid back to the point of horizontal No food till 11.30pm!! Don't they realise we get hungry before then? SLEEP 

** Arrival (Pip, July 12, 1997)
First sight of Madagascar! We got off the plane into weather much the same as we left in England - maybe even a bit cooler. The airport wasmore sophisticated than we expected but the beauracracy experienced at passport control gave us a taste of what - undoubtedly - is to come. We were told that we would meet our guide and the W.C. agent, Shaun. Martin thought that a dodgy Madagascan was "Hamba" but it appeared that this guy was trying to pull him! At customs the EPIRB was confiscated and we were told to return on Monday. Eventually we got two mini-buses which were a bit dodgy and a little Madagascan boy held the door shut! Safety went out the window. Everyone was very quiet on the trip from the airport to the hotel. Very few of us have ever been to a developing country and so we were shocked by the sheer poverty of the people we saw. It sounds like a cliche but can't really describe how it felt - I suppose it was a mixture of shock, pity and numbness and it felt wrong to be on holiday with money in my pocket in a country where life was so hard. The hotel - Hotel Cappuccino - was on a street with no name about 15km away from the airport. We paid about .1.50 per head per night and filled all seven of the hotel rooms. Most rooms had a balcony, bed and bathroom and were of a far higher standard than any of us expected. I was leader from Friday afternoon and after the nerve-wrecking experience at Heathrow, Charls De Gaulle and Madagascan airports I was truly looking forward to handing over to Andrew Stokes; the responsibility of looking after passports and tickets and checking us into the different terminals was extremely tiring. We went for lunch in Tana, and later went to the zoo. Anyone who has watched the film "American Warewolf" will be able to understand how we feel. Instead of new people walking into a country pub and everything coming to a standstill, we are in a foreign country and feel all eyes on us all the time. People stop in their tracks, point and usually laugh at us. It is the strangest feeling walking around in Madagascar. In England, colour is not an issue for whites - except for those who are racist - and so for us, being a minority here it is unnerving. For the whole of Sunday I felt as though I should not be here. Not because I wasn't enjoying myself or because I didn't appreciate a different country but because I felt as though we were patronising this underdeveloped country. What right had we to come to somone elses country? Why had we come here? I decided that our reasons were purely selfish - we had come to see a different culture. I wondered whether the subconscious reason for affluent westerners visiting poorer countries was to reassure themselves about how much we have. It made me realise how lucky I was, and I hope that I don't forget the perspective that I have gained here. 

** A busy day (Pip, July 13, 1997)
Today we had a huge amount of things to do:visit the Embassy collect the EPIRB get supplies for the next weekget passes for Isalo and Ranomafana National Parks find transport get maps Our guide, Nanah, is a really nice guy - sounds corny but he really is sweet. He gets a lot of abuse from the oter Madagascans - he says it is because he is with so many whites. This abuse worsens and becomes more blatant when he is talking to one of the girls on his own. But this abuse is not in any way violent or loud, as it would be in England, Malagasy jibing takes the form of pointing and laughing. This placidity and calmness is incomparable to English behaviour - as is much of the Madagascan habits and culture / society life. I think that the team being split up into smaller groups to carry out the different tasks has helped us, as well as the Madagascans, in many ways. Firstly we get to know say three people a bit better because we are not with so many. Secondly, we start working together to be more involved in the Madagascan way of life; that is insofar as we are not so excluded (or as much of a spectacle). All of these factors help team-building - which sounds corny but is one of the main reasons for us coming here. Also, being in smaller groups is less daunting for the Madagascans, since 19 whites trooping around a city, with very few white inhabitants must be alarming. Andrew took over from me on Sunday night and organised us into groups. We managed to get everything done before it got dark, which was lucky, since wandering aroun in Tana after dark is highly inadvisable - even in large groups. 

** Tana to Antoetra, starting point of the village trek (Pip, July 14, 1997)
Today we left Tana and went South to do our village trek. When we arrived in Madagascar's capital city I found it very difficult to cope with the poverty and hardship that seems to be daily life. But by the time I left I had come to accept that I could not compare the Western way of life with that of Madagascar. These are different countries with different cultures and Madagascar is at a different stage of its development as a country and its current situation is not to be patronised by us. The bus arrived at 8.00 am, we left at 8.30 am and went to the bus owners house to sort out prices and dismantle part of the bus so that we could fit us and our rucksacks (which were growing both in weight and size - or seemingly so - by the day). Once we left Tana the road remained tarmaced and we went a lot faster than we had expected. We stopped at a village called Antsirabe where the locals were having a market. As usual we were pounced upon and encouraged to buy their wares eg carrots, cakes, oranges, wooden ornaments etc. When we said that we wanted to buy some carrots, about 7 Madagascans appeared from nowhere all ofering huge bundles of the said vegetable for us to buy! Mike's excellent haggling skills came in handy, as did our few Madagascan words "Hoatrimona". We stopped again at Ambositra. Here we bought more food, a cooking pot and hats - Graeme's being the stupidest! I met a girl called Nicole who used us as an opportunity to practice here English - who in Engalnd (at 14) can speak Malagasy? Her mother wanted me to swap addresses with her daughter which I did and I intend to write to her. After showing the local children themselves in action on video (which they loved) we left. After an eight hour trip we finally arrived in Antoetra. We were greeted by about thirty children who were incredibly happy to see us; they all had huge grins on their faces and asked us our names. They surrounded the bus which was very strange because in England we would feel intimidated - in Madagascar I felt uncomfortable that they were so elated but it was great to feel so welcome - it was also very funny! We slept in the Village school. 

** First day of the village trek (Pokey, July 15, 1997)
We awoke to another cloudy overcast day. The two guides and porter arrived who were arranged the previous night in a pitch black hut under the watchful eyes of the senior villagers and the "chef de Village". We persuaded them that the route they wanted to take lasting 8 days wasn't an option. We needed to reach Sandrakaley in 4 or 5 days. After breakfast and no small amount of faffing around (the morning procedure was not yet second nature) we were at last trekking with our packs on our backs. As the day unfolded stories of strange dreams were told. Pip had dreamt of people in the window of the school house and shouted to Suzanne to comfort her in her sleep. Mike heard people calling his name and as for myself, I dreamt we were having a number count - "FIVE" - I shouted out and then wondered why no-one else was calling their number. Was the Larium taking effect?? As we left the village of Antoetra several of the children followed us. They were all very friendly, asking our names, telling us theirs and how they were. The scenery was wonderful although the low cloud (for we were higher up than anywhere in the UK) obscured some of the highest peaks. It was discovered that Nat had an uncanny knack of falling over and falling over again and falling over gain...!! The terrain was tough, a lot tougher than we had expected. "An easy introduction to the expedition; to enable us to acclimatise to Madagascar". NO, by the firs tnight of the village treak we were all knackered. We camped at a delightful place called Faliarivo. We pitched our tents on a flat plateau, the land dropped steeply away to woodland, streams and paddy fields. All the villagers came and watched us set up camp and cook, they were all really friendly. The trekking was hard but overall, a thoroughly enjoyable day. 

** Second day of the village trek (Catherine, July 16, 1997)
We got up at 6.30 this morning and had scrambled eggs and crackers for breakfast. We decided to take the shorter route to Sandrakaley which we were told was over slippery ground - we soon found out what the guide meant - sliding down rock faces and scrambling up hills on all fours. It felt like the hills would never end - eventually we came to a village and the sun came out (so did sun hats, sun cream and cameras - the views have been spectacular). Here Suzanne found that she had left her water bottle at the last rest stop and had to run the km there and back to fetch it. We walked through the village slowly with a large audience. The houses had very muddy paths between them and pigs and chickens wandered free range. I don't know what I'm doing wrong but whenever I smile at people they laugh at me! We stopped for lunch on top of a hill - it was really hot by now and we had soup for lunch! The guides have been invaluable as aids up and down the steep slopes. We did not make our objective that evening but had to stop in a little, muddy village - some of the boys had to sleep in the chief's hut as there was not enough room to pitch all of the tents. The people here have been very interested in us - they stood very close watching everything. Dinner was lovely - pasta and several sauces. We are all dying for a proper wash. 

** Third day of the village trek (Graeme, July 17, 1997)
Got up at 6.30 again this morning, I tihnk that some of us are actually getting used to getting up this early. The morning jobs seem to be coming almost routine as the team splits into sub-teams and sets of to accomplish their own little jobs of fetching water, collecting food, cooking or washing up. By this time in the first trek we have realised that because of the terrain there is n way we are going to make Sandrakaley by Sunday on foot. So, we are now planning to walk to Fiandanana and arrive there as early as possible on Sunday, then organise transport to Sandrakaley. Nanah informs us that there is someone there with a car which will fit 15 people in. We set off walking later than originally proposed and again the terrain started off being very difficult especially for our growing number of walking wounded. However we pressed on and at lunch time we were rewarded with being allowed to have lunch by a river providing us with an opportunity to have a wash and wash some clothes. Setting off refreshed and filled up after lunch we started to cover more distance over slightly easier terrain and arrived at Ambaro on the village football pitch. It was here where some of us and Jean-Pierre, the intrepid guide got our first bit of frisbee playing in since the build up. The locals here were fairly imposing, and had to be asked to move by Nanah while we ate. AFter dinner most of us just sat around talking, looking at the moon through binoculars and looking for interesting and humorous shapes in the clouds before retiring to bed for a refreshing and good nights sleep. 

** Fourth day of the village trek (Sally, July 18, 1997)
Today it rained. Yet another early morning, however they do seem to be getting easier. It was Nat's birthday so Hannah woke early in a panic to attach baloons to Nat's tent. On this particularly special occasion we had a fab breakfast of chapatis with jam/peanut butter and tinned fruit - wow! No eggs this morning as the village only had four, 2 week old eggs which we declined to try Again we were late setting off after foot inspections, tent distmantling and general pratting about. We actually made our objective today after finding the terrain a lot less testing. Jean-Pierre actually seemed a little tired today - he is human after all. Today's challenges involved several river crossings. The guides found our preparations hilarious - taking off boots, waterproofing kit. The locals also became our audience and found us particularly amusing. The major river crossing had water coming up to most of our waists - Sam's bum. Nat looked as though she was wearing a nappy. Towards the end of the day, no-one could be bothered to remove their boots so we splashed through much to the disgust of the first aid officers who worried about the problem of athelete's foot etc. The conversation of the day appeared after the major river crossing when Catherine (Saffy) asked for the shovel. Ben was foolish enough to ask why she needed it "I don't wish to walk around with a wet sanitary towel for the rest of the day". To answer this Ben was foolish to say the word "pardon" to which Catherine repeated everything. Dinner for a change was soup and rice at the end of one of the only climbs of the day. Biscuit levels are getting low but we did have Laughing Cow cheese today. Group 2 (Pokey, Sal, Suzanne and Saffy) cooked a banquet for dinner including tuna, noodles, rice (what a surprise) and spinach/cabbage. We camped on a beach which could have been a wee bit embarrassing when it began to piss it down enabling the possibility of being washed away to become apparent. The river water was particularly clean with a friendly pig merrily excreting crap into the water. 

** Final day of the village trek (Ben, July 19, 1997)
After spending an evening on a beach, several members of the team found that their tents had leaked with the heavy rainfall, through the night. Martin was so upset, because his tent was wet, that he began to threaten anyone whose tent was dry. In theory, today was the last day of the village trek, and instead of aiming for our previous destination of Sandrakaley, we set off for the small town of Fiandanana, where, it was hoped, we could obtain transport and reach our project site within a reasonable time. Fortunately, the terrain was similar to the previous day: that is, it was reasonably flat and the team were able to make good progress, eventually reaching Fiandanana by lunch time, which followed an increasngly familiar routine and menu, rice and soup. However, lunch was overshadowed by the need to find suitable transport. The vehicle turned out to be an old Peugeot pickup with no hand brake, no speedometer and a red light flashing DANGER when the engine started (or attempted to). It was also decided that only half of the team could tavel the necessary 25km with their kit at one time. Hannah and Oli, the leaders of the day, had to decide who would go first to set up the tents and prepare for the arrival of the other half; this task was made increasingly difficult by the driver who insisted that the journey to Sandrakaley would take at least 3 hours one-way. It also meant that the group at Fiandanana would not arrive in Sandrakaley until at least 22:30. Unfortunately, it took the first group just 5 hours to reach their destination due to the pickup breaking down. In the first group, we had stopped at the local shop and bought food and drinks including the much needed Thee Horses Beer, essential for a long journey. On arrival we (group 1) prepared a large meal, while thinking of the others stranded, eating just the dried food and rice - and no beer; they did, however have some real Madagascan wine which resembled river water and red dye, more than it did, Vin de Pays, or anything else. On boiling it to make it drinkable, and to remove the suspected large amounts of alcohol, Andrew O apparently became quite high on the fumes! Due to the lateness of our arrival (it was dark) we spent the night in the school house, rebuilt between 1994-97 by Feedback Madagascar - it seems to be holding up to our treatment so far. The villagers are very friendly, and, as in other villages, are fascinated by what we are doing, our food, equipment etc. The project phase should, hopefully, enable us to have a greater understanding of rural life in Southern Madagascar, by aiding them in developing the country and its people. 

** First day in Sandrakaley (Han, July 20, 1997)
Having had a rather bitty-type of a day to be leader on Sunday, it was decided that I had to be leader again on the Monday. As half the team wavedgood-bye to Oli (still assistant leader) and the supplies team who were going to Ifanadine to restock, I was faced with the task of making a three-roomed school house into something like home. In the morning, people were given freedom to do washing, wash themselves and generally relax. Which was nice. However, after lunch, more serious work began to develop in the form of shower building. Actually, the construction of the shower was totally male territory. No women were allowed in the vicinity unless she came bearing tea and biccies!! Meanwhile, the women's work in the school house consisted of clearing fllors of all baggge, sweeping and lugging school desks around the building. We managed, in about 2 hours, to turn the school's rooms into a rather homey place... and I think the men were secretly rather impressed. The male bonding round the back of the building (aka building a shower) was a mixed success. The blokes thoroughly enjoyed themselves... and the girls (namely Suzanne) had destroyed the show by the next morning!! 

** Second day in Sandrakaley (Oli, July 21, 1997)
This was the first day of our project work. In the morning, we went to the two sites on which we would be working. Basically, we were asked to construct plant boxes of 6m x 1m dimensions, using the local tools, which consisted of 2 spades per site, ad pitching forks which bent like rubber! We drew up a time-table for our project work over lunch - it turned out that they only wanted us to do about 12 hours work over 5 days!! We started our plant boxes that afternoon, and my group, particularly, found it harder than it looked (we had to plough half a field with our hands before we could even start!!) That evening, after a hot afternoon's work, what we all really wanted was a really hearty meal. Unfortuantely, Graeme and Sam's 'attempt' at cooking tasted like the bottom of the toilets looked! PS. Since then, the apportion of the blame for this meal has been split as follows:24% - Sam and Graeme (chief chefs)25% - Mike (started it off badly)25% - Martin (should have been cooking)25% - Supplies (ie poor ingredients)1% - Dave (for stirring the rice)Sam and Graeme got off lightly by their own admission. 

** Third day in Sandrakaley (Kay, July 22, 1997)
We set off for work and arrived at the first site at 8 am. After sitting around for an hour, waiting for the people from Feedback Madagascar to arrive with the tools, we decided to find out what was going on. Three people set off for the other site, thn returned having met some people on the way. We eventually started work and did a few more plant boxes, then went back home for lunch. After lunch and a bit of a relax, we went for a wander around the nature reserve. It was rather uneventful, but it was nice to feel that you were in a bit of a rain forest. The evening was designated as games night, but the number of people actually well enough to play was so few, that it had to be reduced to just 3 games (the malingerers were taking up 2 rooms - how selfish can you get?) The night ended with a game of consequences which showed up the more inventive - and one-track minded - people in the group, and was a good laugh. 

** Fourth day in Sandrakaley (Katie, July 23, 1997)
Thrown straight in as leader due to Dave's untimely illness, I gave everyone the chance of a lie-in. Then we wandered to our new project site, digging irrigation channels. Only just over half of us were well enough to go 'to work', not that it really mattered, as there were only two spades. So, the rota system of work meant that we all did a whole ten minutes digging each. Well, most of us, that is, as some people sat around and watched. After lunch, we went back to the nature reserve, and in groups counted trees of various sizes. A local Madagascan told us the names of the trees in our area and we got some heart laughs whilst trying to repeat them. Back at the school houe we had to prepare a report to deliver to the other groups on how many of the different types of tree threre were of specific sizes in our area. Not for any particular reason, just because it would be nice for us to know, I think. Dinner was good - a dessert of pineapple flambe and chocolate sauce rounded it off nicely - and was fllowed by grouping, with some of the locals, around the campfire. Songs were sung and dances were danced, and this proved to be a warm-up for Friday's "goodbye to the locals". Team One's rendition of "The Patio Song", left a lot to be desired, however the Great British Passport Holders were somewhat saved by Sally's solo of one of her Italian songs. This earned her the nickname of Pavarotti; and quite rightly too. The evening passed with Charley earning herself the name "Chunder", not without good reason too, I might add, and everyone being eaten alive by all of the bugs. 

** Final day in Sandrakaley (Dave, July 24, 1997)
And so it came to pass that the good villagers of Sandrakaley bid us a fond farewell with a plate of bananas and the invitation - once again - to make fools of ourselves accompanied by the village's very own popular beat combo. The versatile group of minstrels performed - at our demand - a greatest hits set which was received rapturously by he enthusiastic audience and when the mighty riff of the epic number, Monique, issued forth from the well used instruments we took the opportunity to entertain the villagers through the medium of dance. Forgetting the abject failure of our attempts at both dancing and singing the previous night and the fact that we were now stone cold sober, but showing that great British enthusiasm and resilience we set about publicly humiliating ourselves in an attempt not to have our efforts superceeded by an altogether more competant, but nonetheless foreign opposition. Sam with his all-encompassing, in fact, Mr Tickle-esque limbs proved to be a source of great entertainment as he writhed, twisted and girated before an entranced audience however, spontaneous combustion would perhaps have proved a more exciting, impressive and constructive alternative to our somewhat lacklustre efforts at song and dance. Indeed, Sam appeared to have undergone an amazing transformation from an ordinary schoolboy to a wildly vibrating magician in posession of hypnotic powers. Unfortunately, all good things must come to a hideously embarassing climx and with the end of Sam's masively popular eratic prancing routing came the advent of white man singing. In an effort to save face, we took a dogmatic tone, raised our voices to the heavens and treated the assembled gatherers to a rendition of Jerusalem. Sadly, our attempt to make their African island seem inferior to our 'green and pleasant land' was greeted with modest indifference! However, morale must not suffer with our inept performance; we are British, we brought the art of queuing to the world, we won the World Cup 31 years ago and we have to teach those who fail to recognise our status to show some respect. 

** From Sandrakaley to Tsaratanana (Sam, July 25, 1997)
The day's plan was to walk from Sandrakaley to the neighbouring town of Tsaratanana (this might be spelt wrong, but who cares - not me, that's forsure). However the chance for transport arose, and as the town was about 7 km away, we grabbed it by the balls (but then released it, stroked them better and apologised). However, as we were by this stage used to Madagascan punctuality, we were not surprised by it not turning up on time and left on foot. The transport met us half-way and half of the group clambered in while the others chose to jog (albeit for about a minute). Much hilarity was created when Mike and Martin, travelling by use of legs, were fooled into thinking our place of rest was further on than it actually was while the rest of us hid in a schoolhouse waiting for them to realise and come back, which fortunately they did. The schoolhouse was to be where we would spend that night and was about 5 minutes walk from the village. Feedback had organised a football match for us aginst the locals for which we had meticulously planned for under the guidance of our Captain Oli. However, many of our tactics and game plans were thrown out of the window when we learnt it was to be only 7-a-side. To give everyone a chance to play we decided to have 2 teams and rotate the positions. The teams were: Safe Hands Sam Smasher Pokey Chopper Bloor Razor Reynolds Skipper (Oli) Nanah the Short The General (Martin) and Safe Juans Juan (Mike) Cup-a-soup (Han) Pavarotti (Sal) Thorley Minimus Chunder Charley Biffer Lambert Chuck (Ben)with Helena, Kay (saxophone and timpani respectively). Kick-off was at 3.00 pm and we jogged into the village to the pitch, where scores of natives surrounded the pitch. After a brief warm-up the opposition turned up sporting pink American Eagles tops and flip-flops. The match started frantically and after 5 minutes I found myself facing an indirect free kick just outside the area. The balls was fired towards me and I had it covered. However due to an unlucky bobble on the uneven surface the ball sneaked through my legs and into the back of the net (well, the trees behind). It was an early blow and it took a few excellent saves on my part to convince me that my hands actually were 'safe' after all. And so the match wore on in the afternoon heat with some excellent performances from our very own foreign transfer Nanah, Skipper and the General. After a few team changes we were soon 2-0 down and looking weary. However, the General put us back in the gam with a piercing firecracker of a shot that lef their keeper standing. 2-1. Unfortunately more defensive errors followed and Safe Juans was left helpless to their strikers powerful (bare) right foot. Skipper then went on to score us another goal, bizarrely by simply walking past the goalkeeper with the ball at his feet. Game on! That is until they scored again. Bullying of the keeper by Ben worked to no avail and the game looked lost. However, 10 minutes from the end a balls was crossed in front of their goal and Skipper's towering dominance allowed him a header into the goal. Game on! That is until the final whistle was blown, final score 4-3 to the local team. Although tired and sweaty we congratulated the winners in high spirits and were treated to free Fanta. The evening meal was cooked for us by members of Feedback and we ate the meal of Zebu stew, rice and unknown vegetables with them in the schoolhouse along with the village chief and the main teacher. Thanks were exchanged after the meal before we moved outside around a campfire. We were then treated to some traditional songs and dancing. I was then made to look stupid once again by blindfoldedly stepping over non-existent children, the humiliation of which will haunt me forever. 

** Travelling to Ranomafana (Helly, July 26, 1997)
We got up and packed early and ready to go. 20 packs and 20 people, expecting a large and roomy Mazda Van, however, a little Nissan Van arrived. Sardines, definitely packed live sardines. We all had a bumpy journey along the track out of Tsaratanana towards Ranomafana. We all sat perched on our rucksacs bouncing up towards the roof as we hurtled over the bumps. At Afannadine, we stopped to stock up on chocolate, which is of course much more important than things like petrol. After about 10 minutes in Afannadine we all piled back into the truck and back along a flat tarmac road towards Ranomafana. Many tortured faces as we bumped and banged around the back of the van. We were dropped off at the 'Hotel Manja'. About 20 raised wooden bungalows, 6 of which we occuppied. Lunch was in the hotel restaurant, real meat and non-gritty good was very welcome, as was a cold drink. We spent the afternoon visitng the thermal baths. Warm water was heavenly, and the clean, hot shower very much needed. All clean and refreshed we wandered back to the hotel. Between returning and dinner a group of us wandered into town to look for souvenirs. We were desperate to buy hats but a bit dubious as to whether they would survive Isalo. In the evening we all ate together in a rather small room, and after a good meal started the quiz, Bernard losing their lead. After an enjoyable evening a soft matress was very soothing as was the comfort of the mosquito net. Our day of return to civilisation. 

** First day in Ranomafana National Park (Andrew, July 27, 1997)
A good night in a comfortable bed and a big breakfast and we were ready to start preparing for the next phase. Transport people arranged transport, supplied raided the market and accomodation hit the phones to plan ahead to Tana. Everyone was busy. All was completed by 11 am, and two consecutive groups headed off for the National Park stopping off to look at the spectacular views of rainforest and the waterfall. The campsite was great, showevers, loos and even little covers under which to pitch your tents. We were ready to start our next phase. And so it began - tents were set up whilst a small team went to source guides for our 2-day stay. We had planned to do a walk in the afternoon - perhaps to a scenic spot on the river so people could have a wash etc. We had all read the guide books and decided that an evening/night walk would also be good for lemur spotting. The guides seemed to prefer the plan of a long afternoon/evening walk combined. Since we were base-camping and leaving all the heavy stuff at the campsite, there was little objection. After a large lunch following the morning's resupply mission, we were ready to go. For the first time on the expedition, I felt like a tourist on holiday. The paths that we started on were paved with stones, steps had been cut and there was a huge iron bridge over the river. It was not long before we'd left this behind and moved on to lesser trails, most of which were still well trodden. As we moved deeper into the rainforest, we started to see what it was really like. I was expecting a really dense green jungle with a hot and humid atmosphere. It came as quite a surprise to discover that this great rainforest was not all that far removed from an English wood. There was, however, one very great difference. Lemurs - in total we saw 7 different species while we were in the part. They were: gray gentle bamboo lemur red bellied lemur mouse monkey greater bamboo lemur spotted lemur red fronted brown lemur Verreaux's sifakaThe guides should be commended for the way they managed to allow all members of the team to see so much of the wildlife. Like tourists, we all partook in a camera-clicking frenzy. I am confident that we will all have difficulty trying to convince friends and relatives that the black splodge on a background of trees and sky is in fact a lemur. Such is. The guides asked us to bring an assortment of sardines and bananas along 'for later'. Indeed following another quick sunset, we retired to a clearing often frequented by the local lemurs. Baiting them with a scattering of sardines on the floor and bananas smeared on a tree it was not long before the opportunity for a photo shoot arose. Remarkably, the lemurs seemed completely unphased by the strobe-lke effect of 20 camera flashes all going at once. Being able to see the endemic wildlife within arms reach is an experience I don't think anyone will forget. As it was Hannah's birthday, we were again treated to an excellent evening meal when we returned. The chips were finished off very quickly and bananas and custard dessert was a very refreshing change from the usual pineapple. 

** Second day in Ranomafana (Charley, July 28, 1997)
As I awoke to my new responsibilities as leader I thought I was in for a stress-free day... a morning trek through the rainforest and an afternoonto fill... which would come to a thoroughly satisfying end when Nanah returned from town with our beer! Little did I know how we would 'fill' our afternoon.. As we left the campsite our guides told us that we were off into the bamboo forest in search of more lemurs. Along the way our guide developed a curious habit of stopping every so often to pick up the odd leaf or flower. I was intrigued, but fearing some rain forest fady, I didn't ask.. all was then revealed. We stopped for a water break and the guide asked us to gather round whilst he shared some of the truly remarkable secrets of the rainforest with us. He amazingly showed us leaf after leaf, flower after flower, told us its name and then went on to describe its healing qualities. We witnessed everything... from cures for the comon cold to anti-rheumatism agents! Martin acquired some large looking green leaves complete with instructions and a description of exactly what they would do for his legs! The group seemed totally in awe of the rainforest's healing powers - we all wondered how on earth such powers were ever detected in the first place. It is remarkable to think that whilst the devleoped world still strives to perfect its medicine a developing country such as Madagascar has discovered so many effective medicine substitutes. As we wandered further into the rainforest we witnessed more lemurs and... funnily enough... whilst in the bamboo forest we greeted several bamboo lemurs! Amidst a flourish of camera flashes I noticed that in the National Park the majority of lemurs wear collars and tags and whilst I know that this enabled the Malagasy people to conserve their wildlife it seems sad that tourism has resulting in guides being able to locate a lemur at a moments notice. Upon our return to camp for lunch it was established that the afternoon would be spent discussing the next phase of our expedition... Isalo National Park. Martin, Nat and Suzanne pointed out that whilst in Isalo the whole team should, and indeed wanted to be, physically challenged. However, what is a physical challenge to one is a leisurely afternoon stroll to another! And so I was to discuss the options with the team and we were to establish a rough itinerary. A healthy debate followed... much was discussed... and being the focal point of a heated debat was not exactly fun! Should we split the team? Should half have a rest day? Which route should we follow? Is that distance possible in one day? But Charley, you din't tell us that the group with only 1 'adult' would have to remain at camp due to safety... arghhh! It has to be said that not a great deal was decided on - we would split the group for one day - when and where would be discussed with the guides in Isalo - but the team was now aware of the options open. The afternoon was spent on what has to be called a rather unsuccessful swimming and fishing expedition... Hanah, Pokey and Martin were impressed with the HUGE termite that they found and prompty chopped in half to us for rather pointless fish bait! The evening passed around yet another stunning campfire... and dried rations taste so much better under a beautiful starry sky and with a bottle of Three Horses Beer in your hand!! 

** Ranomafana to Fianar (Pokey, July 29, 1997)
Until this stage the transport group had done us proud with some fine buses and trucks. However, with all due respect, the "bus" arranged to take us from Ranomafana to Fianar was a touch on the small side. 16 of us crammed into the truck with packs on the floor of the truck and piled so high on the roof it looked like it might topple over! Mike, our leader for the day, was vehemently cursing his tent-partner, Ben, in his absence for the absurdly small truck. After our arrival in Fianar, Ben, Sal & Suzanne were not far behind us, having travelled by a Mazda truck. Their journey in a car, which apparently had not suspension and nothing to sit on meant that they regularly struck their heads against the roof, was obviously more uncomfortable than ours, judging by their shell-shocked appearance. I actually quite enjoyed the joyney and my tape was accepted on the semi-function radio/cassette player for much of the duration; which was great. On arriving in Fianar, we stood in awe of the Tsara Guest House with its smartly painted, peach coloured walls and well finished window frames. Surely this was a facard. But on entering and after being directed to our rooms, we weren't disappointed. All the rooms were stylishly decorated and complete with smart wooden fittings, with even a few ornaments here and there. The best was yet to come. On investigating the bathrooms, hot water positively gushed from the taps, there were good showers and flushing toilets. This place was certainly "out-of-place" and still the best was yet to come. A few of us went down to the bar where hot chocolate and coffee was ordered. It was fantastic, obviously made with real milk!! Obviously we decided to have lunch at the Guest House, which for many; those with good "menu intuition" was of large steak sandwiches. There were many pleas to drop our intended itinerary and stay put for the remaining time. The afternoon's jobs were to get transport to Isalo and to get enough supplies or the whole of the Isalo trek. A new supplies team was put on the case and, with a better idea of just how much food 20 people could eat, we set about buying loads of food. Having nearly finished our purchasing, we met a man from the "Tourist Office", so he said, which certainly surprised me, but he spoke good english. I soon realised just how fortunate we were to meet him. The subject of meths or the lack of it, was one which had grown particularly close to my heart as I was in charge of equipment. Obviously, I was overjoyed when the man told us he knew where we could get some. So, meths was found and bought. The supply buying frenzy was completed on arrival at the market where we purchased 1 mans entire stock of ranges. Meanwhile, I think Martin was slightly unnerved by the bloke with an 18 inch knife watching our every move. We returned safely to the Tsara Guest House with a kit bag of over 100 oranges costing just a few pence or less each. Meanwhile, transport (Werthers, Sally, Helly and Mike) told stories of the bus they had hired, which got the Werthers thumbs-up and more "rocking". We ate our evening meal in the Tsara Guest House and afterwards, some more noisily than others got quite rat-arsed. It particular, Katie, who was well gone, managed to leave her walking boots and a cherry lolly lying about the hotel before going to bed. 

** Fianar to Ranohira -- the storm (Sally, July 31, 1997)
At the crack of dawn a few hardy members of our team - Pip, Pokey, Graeme and Martin went to the bakery to get 100+ hot, fresh baguettes so that our supplies for the joyney and next few days would be complete. May I remark how nice it was to eat fresh bread for a change instead of the har,d smoky bread that we had become accustomed to. I feel I must remark on the military-like operation carried out by this provisions team in sorting out the supplies nto kit bags. Pokey had a list in his notebook of the contents of each kit bag. By now we were getting the measure of good organisation. A little later than expected (although we were used to Malagasy timing by now) our fantastic bus arrived to take us to Ranohira. At this point I would like to describe the bus that Werthers, Mike, Helena and I had found and bartered for the day before. It had curtains, a first aid kit and very comfy seats. In fact the only word for this bus was ROCKING. This journey would turn out to be a very exciting one. Firstly we stopped to look around a paper making place - Malagasy style. Everyone got a sample of this hand made paper which I though was very kind of them. At this point I remember that Kay wasn't feeling so good, she'd obviously been eating too many biscuits. The day had started off fine and sunny but as we travelled further towards Isalo the sky clouded over and in the distance we could see a large storm brewing. We stopped to have a good look at a huge rock which just stood out in the middle of nowhere. It was most impressive. As we continued on our journey, it became very cold and on the side of the road we observed ice. Now this was a very strange site in the middle of a very arid environment. What with this sight, a humungous storm and The Prodigy blasting from the radio it made the whole experience extremely eerie. As we entered the middle of the storm and lightning feel about s we had to comfort Katie as she though we would all die of a horrible death by electrocution. On this treasured day we also encountered our first Baobabs which are very strange trees. These were seen and photographed so that I think that everyone in our team possesses the same photo. The only thing that spoilt our day was that on arrival in Ranohira we found that the hotel had no rooms. Thus we were forced into staying at the Hotel Joyeux Lemurien, a dodgy place with a poor excuse for a restaurant. The rooms were pokey little holes with creepy crawlies and plenty of blood thirsty mosquitos. The restaurant was crap. We all sat at a very long table in the dark and waited for ages for a meal to appear. When it did eventually come it was very unimpressive, in fact is was crap and eneatable. AND there was no pudding. However, the worst thing about this hotel was the toilets, which were the worst smelling crap holes in the history of the world (except for the maggot infested ones on the provisions trip on the project phase). To top it all off, when we went to pay the bill the following morning, the old 'innocent' hag saw us coming and charged us for 5 star accomodation. We were not happy. 

** First day in Isalo National Park (Oli, August 1, 1997)
After a fairly leisurely get-up, I took over the leader's whistle from Catherine, at about 10.00 am. As we left the Hotel Lemurien (seemingly the local haunt of the towns cockroach population) and headed for Isalo National Park, I was expecting this to be the highlight of the expedition. We stopped for lunch at midday, when we arrived at a beautiful spot by a river and took ample time to consume and digest our french loaves with various fillings. After an extended dinner break, we set off at about 2.00 pm. It proved to be a comparatively easy day, as we covered 12 km in roughly 5 hours, including lunch. This meant we arrived at the campsite just about 3.00 pm. It was superbly situated under a cluster of Mangrove trees and was like a gateway into the canyons. After the customary task of tent-erection, Graeme, Sam and myself decided to venture into the Canyon des Singes (pronounced sinj!). It proved worthwile, as we were suddenly encapsulated in a hidden paradise. Following a good half-hour's exploration, we were swiftly persuaded to return o base camp, by what sounded like the deranged warblings of a drowning beast! Although we were impressed with our adventure, on returning, the rest of Madagascar Team One seemed more concerned with removing jiggers from their feet! Mike amassed a formidable total of 3 jiggers (one of which was apparently a beast) while Martin and Nanah proved themselves worthy jigger surgeons. A career in medicine surely beckons for them both. And so dusk fell, with great discretion. With the night came a chill and with the chill out cam ethe recently purchased Malagasy rugs. As we polished off another fine meal (disturbed only by a hairy caterpillar, trying to crush our high spirits by stinging Werthers; who coped valiantly) a storm brewed in the distance. We were able to watch the lightning, miles away, piercing the grey skies, safe in the knowledge that our rugs would protect us! 

** Visiting the Canyons in Isalo National Park (Sally, August 2, 1997)
After an uneasy night's sleep, when wild dogs roamed around the campsite we awoke to breakfast of soup and bread. The guides then led us into the Canyon des Singes where we came close up to the first ring-tailed lemurs that we had seen on the expedition. The canyon was a lush green paradise in the midst of the hot, baron landscape of Isalo. We sepnt the morning trekking deep into the canyon, clambering over rocks which, had we had our big rucksacks on - would have been near impossible. A group photo was taken by the guides, of us all on a huge rock. Unfortuantely, some photos were ruined by an extremely rude foreign man walking straight in front of us. We returned to the campsite for lunch which conssted of Tuc biscuits (Which we soon became very sick of), sardines, tuna and good old Laughing Cow cheese. The guides did not want to set off again too early so Martin took the opportunity to remove min and Graeme's jiggers. There was no pain (it's all in the mind) while Martin was digging around with a pin in my little toe, but he successfully removed my jigger to leave a slight crater in my toe which I have to admit did sting slightly when iodine was put into it. In the afternoon, we set off on a shorter trek in the Canyon du Rats. At one point an adventurous group set off to clamber over the rocks, to explore the nearby area. About a quarter of an hour later they returned with Graeme looking like a drowned rat because he'd falled into a sacred pool thus he was now blessed with eternal life. We then returned to the campsite, sighting several tobs on the way. Dinner consisted of dried food and pasta. I must say that I feel sory for Suzanne and Catherine because both the vegetable chilli and curry (which are exactly the same) are exceptionally grim. At least the meat ones are edible. We all got an early night's sleep as we had to get up at 4.30 am the next morning. I had the job, as leader, of getting everyone up and ready to leave by six. Everyone was ready by this time except Suzanne and Martin who must be the two most disorganised people on our expedition! 

** Trekking in Isalo National Park (Dave, August 3, 1997)
It was that time of day usually reserved for breakfast television presenters and smugglers; indeed, it was half-past-four in the morning that the intrepid squadron arose to take on the challenege of crossing the baron and hostile desert that was the Isalo National Park. And at the end of our quest? -- the post of gold at the end of the rainbow, the greatest accolade, the tomb of Tuten Kahmon, a large deep pool: the Piscine Naturelle, into whose tranquil waters we could plunge, breaking the aqueous serenity like ducks to water. But sadly some failed to realise the importance of our mission, despite the thorough and comprehensive briefing that I, Q, had administered to my aspiring Bonds only the night before. It still grieves me to report that there were some members of the team severely lacking in moral fibre and unable to shake a leg at the appropriate hour. Despite the small minority of cads and their tardy reveille, the piscine marsh was not hindered. With cat-like tread, we began our stealthy trek - pausing to watch the sunrise on its rebellious subjects, we began the ascent of the formidable Isalo massifs which proved the blockade between us and freedom. Those imposing hills, the searing sun and the heavy storm of pervasive locusts proved little challenge for strong-minded expeditioners and we lunched by a stream, eating the pestilent creatures that had conspired to block our path in a glorious gesture of poetic justice. And it was proved to the treacherous doubters, who cast aspirtions on the wisdom of a 4.30 am start, that Q knows best. The lions share of the afternoon was spent reaping the benefits of our physical challenege in the ice torrents of the Piscine Naturelle. So, having demonstrated the capabilities of a fully operation fighting unit, we were only left the task of proving our superior intellect. The combined forces of Sam, Oli, Kay and Katie met this challenge admirably, scoring a full ten out of ten on their joker round of the Sunday-night Pub Quiz. Today proved as stiff a test as any rebel alliance will ever meet and a glimmer of hope for the continuation of the Human race. 

** Return to Ranohira (Sally, August 5, 1997)
The last day of trekking came quickly and it was an extremely sad occasion because although I was looking forward to the R and R, this signified the beginning of the end. We walked in a long meandering line from the Piscine Naturelle into Ranohira laden with our packs for the last time. As Hannah and Katie proceeded to perorm the Hokey Kokey, I couldn't believe that this was the end of our trekking. In a way it was a relief that we had made our final objectives but it also meant that in about a week's time we would be going home. Ranohira came into view as the Gravy Diggers sang their last medley together. It was the end of an era. We all smelt really bad, not that we particularly noticed, and so some of us bought T-shirts and changed into them. What a refreshing change! Our first mission was to eat lunch - not rice, and have a good cold drink. We stored our packs and at lunch. It was then time for a swift wander around Ranohira before departing for our second football match of the expedition. There were lots of strange men in little bits of leather playing football which was a bit scary really. Unfortuantely we lost the football and were also cursed by a paricularly nasty boy in the annoying group of children which surrounded us on the goal line. These children were a cause of much distress to some as they kept poking and prodding us and would not leave us alone. After the football we walked back into Ranohira to find the hotel. There were very few women around but lots of men holding hands! Ranohira was the first place that we had met hostility and that we found the people quite strang. It was a very uncomfortable place here you were never 100% sure about being there. Perhaps it was because it is subjected to more tourists being next to the national park and so they resent it and feel bitter than their lives are continuously invade by foreigners. I was extremely relieved when I found out that we were not staying at the Hotel Joyeux Lemeiurs which had been the worst "hotel" that we had stayed in. Instead we were staying at the Hotel Chez Thomas which was much cleaner with nicer toilets. They did not have a restaurant and so we cooked on our tangias outside the rooms. That night was a particularly restless night for many. In our room (Charley, Han, Katie, Nat and me) the night started off by Nat almost setting fire to our room by burning the Mosquito repeller which Han and I had to put out in a mad rush of stamping as Nat, Katie and Charley went into hysterics. In the middle of the night we awoke to find that Katie was feeling very sick and so Han, Charley, Nat and I decided to have our midnight feast of chocolate and biscuits. Katie at this point rushed outside to be sick and came back in a few minutes later feeling much better so we offered her some chocolate. This was followed by a mass trek to the toilet before going back to sleep. No one slept in as we were all rudely awoken by a very loud inconsiderate turkey. Other strange happenings in the night had occurred including Werthers being attacked by a load of scorpions which were stopped by him closing his sleeping back tightly around him! 

** Boat ride from Tulear to Anakao (Katie, August 7, 1997)
We woke up, albeit a little bleary-eyed after an evening of high activity, much boogying (to the Spice Girls amongst others) and even heated passion in a couple of cases (yes, Sally and Pokey finally got together) at the infamous Zaza, to a breakfast of honey, break and hot chocolate at the Dera. After which we were greeted by a veritable cavalry of pousse-pousse to take us to the docks where our road to paradise awaited us. Three suspicious-looking boats bobbed around on the murky water in which did not dare look too closely as I and several other dare-devils 'volunteered' to test out the vehicle. Martin was looking sceptical and somewhat anxious, as our boat, without leader, drifted out to sea (leaving seven of the team stranded). Yet it was decided after an excruiciating half-hour of "will we ever get back" that they were sufficiently road-worthy to take us the two-hour journey across the idyllic, turquoise water under the perfectly blue clouless sky to the paradise beach at Anakao. Hmm, well that was the initial expectation. The journey did, much to everyone's surprise, pass without incident (a couple of members were sea-sick) and one boat had to have water bailed out, but hey that's nothing for this country), until, that is, after landing up on the short, the sky begins to turn a worry dark grey and the wind beings to pick up. Great fun -- a tropical storm. As Oli and I walked along the beach (which incidentally had a couple of six-toed foot prints - had Sam already been here?) to get to what we initially thought to be our resting place for the night, the rest of the group sat on the beach and watched the storm loom ominously closer. As it came to pass, the hotel actually had no rooms available for us, nor could we camp on the beach, so after a little persuasion of the villagers, Nanah found us huts for the night. Sitting on the veranda, we became somewhat battered as the breeze grew to a gale and the showers grew to downpours. After a discussion of our plan of action, acompanied of course by THB, an extorsionately expensive lunch was munched. Thankfully, the storm did not last long, merely an hour or so, by which time it was late afternoon. After my initial hysteria of "what the hell are we going to do?" I became somewhat calmed and pensive as to just what was the meaning of life, as I wandered along the beach dropping amazing sea-shells into my now, somewhat disfigured basket. With the evening approaching most ofthegroup gatheed on the beach to watch the sun sink softly behind the horizon, turning the sky from blue to pink to black. Now, almost completely soothed and somewhat romantised by the view before us, there was just time for a game of 7's outside on the long picnic benches before a tea of fish, fish and more fish. Nice Dave, once again, lived up to his name and reputation when upon Kay's sickness, wondered if we were both alright. The huts themselves were hot, stuff but a great thankyou must be delivered to the villagers themselves for letting a bunch of frightful loud westerners inhabit their homes for the evening, and in some cases - Kay, even break their ornaments. 

** Return from Anakao (Sam, August 8, 1997)
I took over leadership from Katie after an excellent lunch of octopus curry at 'Les Mangroves'. The first job was to get us back to Tulear where we were hoping to be able to book a room at the Dera. Transport was to be two pick-up trucks. Although still extremely cramped they were a comfortable alternative to pirogues. On reaching Dera we had our first problem. It was fine to eat there in the evening but they had no spare rooms. However, they let us store our kit there while we searched for somewhere else. Nanah, Katie, Oli and myself left the others at the hotel to try another. We took a 2 minute pousse-pousse ride to the Hotel Sud that had plenty of rooms, all of which were very spacious. On the way back to the Dera to tell the others Oli and myself were unfortunate enough to hail the town's slowest pousse-pousse and the driver/puller walked the whole way bac, making a two minute journey last 10. Once settled at the hotel the next couple of hours were taken up with souvenir shopping in the town with things ranging from wood carvings of semi-naked wrestlers to Lacoste shirts (fake). That night was to be our awards night and so once returned from shopping we dressed up in our chic evening wear - sarongs for the girls, bow ties and cummerbunds for the boys. We then made our way to the restaurant, our fantastic attire unfortunately hidden under the black of night. Once settled down to our meal unfortunately things once again were no so rosy as various people were feeling ill. Therefore the awards were abandoned and the group was split into two; those who wished to dance the night away in the haven that was Za Za, and those preferring the tranquility of their hotel beds. After a strenuous night on the dance floor (Us: when do we go Nanah? Nanah: We go when we stop having fun!) we left the Za Za Club in the early hours. Outside the building was a giant congregation of pousse-pousses, each eager for you to be their client. We splt into twos, a boy and girl for safety reasons, and chose a strapping bloke to pull us. Half way through the joyney, most of the boys swapped places with their drivers and we all raced back to the hotel. Dave and I were engaged in a tight battle until he took a completely wrong turn, completely oblivious to his driver shouting from the back. Needless to say, we all got back knackered. 

** Return to Antanananarivo (Sam, August 9, 1997)
Next day's target was to get back to Tana and involved getting to the airport in the morning. Everything went smoothly until it was time to get onthe plane when it became clear that through poor design, there was not enough luggage spce for all the passenger's luggage when the plane seats were full. Although I would have been happy to sit on my rucksack as we had had to do with every other transport we had been on, this was not allowed and we had to leave our luggage sitting on the runway, safe in the knowledge there would be another plane for it 'in a few hours'. On landing in Tana we had to now retrieve our luggage. We did not have time to wait at the airport and we felt it was the airlines responsibility to have our luggage sent to our hotel, free of charge. However, the representative we spoke to was having none of this and it took some forceful persuasion from Suzanne to get them to agree. We took a minibus from the airport, 'sans' most of our rucksacks, to the hotel in which we stayed in at the beginning of our expedition, Hotel Cappucine. However, on arriving it surfaced that no rooms had been booked and we would have to look for somewhere else. However, the owner offered the use of her phone to do this and we soon found somewhere in the other end of town. Next transport was taxis as we all trundled off o the Hotel Anjary. Now settled in this hotel we still ad the problem of luggage. Half the group's luggage had actually fit on the plane but the rest of us were not able to change and had to go out in what we had been wearing for the past few days. As people were generally feeling better we decided to do the awards in the restaurant we ate in that night which, coincidentally, we shared with the other group. The awards and speeches were all performed and received with aplomb and all those involved should be praised. Once again it was a depleted group that hit the clubs (Amnesia) with some ill, notably Suzanne who had been feeling off colour the past few days, but most tired. The next day's jobs were to retrieve the luggage, which had arrived at the Cappucine late the previous evening, find Nanah who we had not seen in 24 hours and organise transport to the airport to go home. Thankfully all were done successfully and my unlucky reign as leader was finally over. I passed the crown on to Charley, safe in the knowledge I could chill all the way home. 

** Returning home (Pokey, August 10, 1997)
With Sam deposed, Charley took over the role of leader for our final day on Madagascar's shores. We had breakfast in a cafe across the road from the Hotel Anjary and then split into 2 groups. One group's task was to retrieve the luggage, which had been left in the Hotel Cappucino for us. The other group set abot getting transport to the airport and buying souvenirs. With my rucksack being one of those left on the runway, I went with the first group, but I was sceptical as to how many rucksacks we'd fnd. Thankfully, a full completement of rucksacks were found, along with a note from Nanah. He'd been earlier to collect his belongings and would see us later. The joy well-done, we also set about buying souvenirs. Bottles of Three Horses, T-shirts from Le Champion supermarket and an excellent tin Air Madagascar plane would perhaps remind me more of the grountry and my sparsely-clad wrestlers. We had lunch in the Hotel Colbert where the steak and crisps for main course and strawberry juice came highly recommended. Here, Nanah reappeared and gave Martin a boat whilst we thanked him with some bicycle lights. We left "the vibrant city with some crazy characters" behind and travelled to the airport for 3.00 pm with out flight at about 9.00 pm. We queued for ages and there was a moment of panic when this very journal was lost, but thankfully retrieved shortly from a member of the airport security staff. Once airbourne, and being a Sunday, we completed the final round of the Sunday night Pub Quiz. To cut the long, long journey short, we landed in Nairobi where we all stayed on the plane and agin in Charles de Gaulle, Paris where we didn't. We reached Heathrow at about 1.00 pm (Monday 11th) where we all bid fond farewells to Suzanne. Relieved to find the trusty Bassetts' bus ON TIME we embarked and soon found ourselves sipping ice cold milk and chewing rather nice (blue!) Allsorts at a service station amidst the metropolis that is Birmingham. It being 5.00 pm and we being ahead of schedule, we telephoned our loved ones to be picked up at 6.00 pom. All were pleased to speak to their parents, except Mike, who, much to his disgust found that steak and chips awaited him at home. All eagerly awaited a hot bath and a comfortable bed. We were finally there. Home. 


